### ISSUE TITLE
Authentication Scheme not changeable and does not adhere draft spec

### ISSUE THREAD

**Issue by blacktemplar** [DavidLievrouw/HttpMessageSigning#2]
Currently this library produces authentication headers with the scheme `SignedHttpRequest`, but the draft spec specifies in section 3 (https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-3) that the scheme should be `Signature`.

I propose either the option to change the scheme name or/and to default it to `Signature`.

**Comment by DavidLievrouw** [comment]
Yep. Thanks.
I'm on it for v4.0.0.
