### ISSUE TITLE
Allow (created) and (expires) headers

### ISSUE THREAD

**Issue by blacktemplar** [DavidLievrouw/HttpMessageSigning#3]
At the moment the library does not allow signatures with (created) and (expires) headers (see https://github.com/DavidLievrouw/HttpMessageSigning/blob/91ff1c412097148cb771f6793df143bdd3517d7e/src/HttpMessageSigning/SigningSettings.cs#L58).

In the current draft those headers are recommended so I think support for those is very important.

**Comment by DavidLievrouw** [comment]
I interpreted it differently: https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-2.3

```
2.  If the header field name is `(created)` and the `algorithm`
       parameter starts with `rsa`, `hmac`, or `ecdsa` an implementation
       MUST produce an error.  If the `created` Signature Parameter is
       not specified, or is not an integer, an implementation MUST
       produce an error.  Otherwise, the header field value is the
       integer expressed by the `created` signature parameter.

3.  If the header field name is `(expires)` and the `algorithm`
       parameter starts with `rsa`, `hmac`, or `ecdsa` an implementation
       MUST produce an error.  If the `expires` Signature Parameter is
       not specified, or is not an integer, an implementation MUST
       produce an error.  Otherwise, the header field value is the
       integer expressed by the `created` signature parameter.
```

Additionally

```
 It is out of scope for this document to dictate
   what header fields an application will want to enforce, but
   implementers SHOULD at minimum include the `(request-target)` and
   `(created)` header fields if `algorithm` does not start with `rsa`,
   `hmac`, or `ecdsa`. Otherwise, `(request-target)` and `date` SHOULD
   be included in the signature.
```

Since only RSA and HMAC are currently supported, it would appear that `(expires)` and `(created)` are never allowed, hence the `throw` statement.

Am I correct?

Secondly, it appears that .NET does not allow '(' and ')' symbols in header names. See https://stackoverflow.com/a/51039555. So we would have to deviate from the spec.

**Comment by blacktemplar** [comment]
> Since only RSA and HMAC are currently supported, it would appear that `(expires)` and `(created)` are never allowed, hence the `throw` statement.

In [Appendix E.2](https://tools.ietf.org/html/draft-cavage-http-signatures-12#appendix-E.2) the draft states that all algorithm names except "hs2019" are deprecated, therefore (created) and (expires) are always allowed in my opinion. Maybe there is also an error in the spec (see [this issue](https://github.com/w3c-ccg/http-signatures/issues/110)). As a side node hs2019 support is missing in your library. I will create another issue for that.

> Secondly, it appears that .NET does not allow '(' and ')' symbols in header names. See https://stackoverflow.com/a/51039555. So we would have to deviate from the spec.

`(expires)` and `(created)` are not real headers but pseudo-headers such as `(request-target)`, which you already support. See also [this comment](https://github.com/w3c-ccg/http-signatures/issues/80#issuecomment-523940625) which proposes to change the name of the headers paramter to clarify this situation.

**Comment by blacktemplar** [comment]
Looking through your commits: I think you misunderstand something ? `(created)` and `(expires)` are never sent as real HTTP headers, their values are part of the Authorization header (i.e. they are parameters given by `created=...,expires=...`)

**Comment by DavidLievrouw** [comment]
Now handling `(created)` and `(expires)` headers as virtual headers, as defined in the spec. They are supported now.

Still, when sending any of the deprecated algorithms `rsa`, `hmac`, ..., and you include the `(created)` or `(expires)` header in the signature string, a verification error will be returned (as specified in the spec).

```
2.  If the header field name is `(created)` and the `algorithm`
       parameter starts with `rsa`, `hmac`, or `ecdsa` an implementation
       MUST produce an error.  If the `created` Signature Parameter is
       not specified, or is not an integer, an implementation MUST
       produce an error.  Otherwise, the header field value is the
       integer expressed by the `created` signature parameter.

3.  If the header field name is `(expires)` and the `algorithm`
       parameter starts with `rsa`, `hmac`, or `ecdsa` an implementation
       MUST produce an error.  If the `expires` Signature Parameter is
       not specified, or is not an integer, an implementation MUST
       produce an error.  Otherwise, the header field value is the
       integer expressed by the `created` signature parameter.
```

Since we now report algorithm `hs2019` by default (#4), `(created)` and `(expires)` are allowed by default too.

Thank you for your useful input.
