### ISSUE TITLE
Instantiate IRequestSignerFactory without DI

### ISSUE THREAD

**Issue by brz** [DavidLievrouw/HttpMessageSigning#36]
Currently, the only way to instantiate an IRequestSignerFactory is by using DI (after reading the wiki). I also noticed the classes are marked as internal which prevents my from instantiating them manually.

I prefer not to introduce DI frameworks in my application for one library.

Is this something you would consider changing in future versions?

**Comment by DavidLievrouw** [comment]
The `Dalion.HttpMessageSigning.Signing` package depends on `Microsoft.Extensions.DependencyInjection.Abstractions`. Changing that would be a major refactoring, I'm afraid. 

A couple of reasons why we do this:
- There are quite a lot of _wrapper_ packages that enable usage of these methods in your DI container of choice, e.g. [Autofac.Extensions.DependencyInjection](https://github.com/autofac/Autofac.Extensions.DependencyInjection).
- It enables well-known DI patterns for developers already used to DI in .NET Standard/Core.
- It allows us to not have to write plumbing code to wire up internal services.

An alternative would be to use some kind of _[poor man's DI](https://blog.ploeh.dk/2014/06/10/pure-di/)_, effectively achieving the same thing, but not using the libraries that are common in .NET Standard-targeted libraries. We could then add custom wrapper packages for each supported DI container, one of which could be `Microsoft.Extensions.DependencyInjection`.

Some ideas:
- Introduce a static `RequestSignerFactory.Default` property, which returns a composed `IRequestSignerFactory`:
  - You would lose any hooks that enable you to modify composition.
  - You will still have a nested package reference to `Microsoft.Extensions.DependencyInjection.Abstractions`.
  - This will make it harder to test your consuming code.
- You might also create a helper method in your containing application, wrapping the usage of `Microsoft.Extensions.DependencyInjection`:
```cs
        public static IRequestSignerFactory GetSignerFactory() {
            var services = new ServiceCollection().AddHttpMessageSigning().Services;

            var provider = services.BuildServiceProvider();
            var signerFactory = provider.GetRequiredService<IRequestSignerFactory>();

            return signerFactory;
        }
```

That would, of course, require you to reference `Microsoft.Extensions.DependencyInjection` in the containing application. And it might be advisable to wrap the creation of the `IServiceProvider` in some kind of caching mechanism, e.g. making it `Lazy<T>`.

Let me know what you think.

**Comment by brz** [comment]
When looking at the code I was indeed afraid that this would require a significant rewrite.
I really like the first idea, where you return an instance on the `Default` property, as I think this will suffice for most use-cases.
Since I'm short on time, for now I will implement the second idea as I'm already familiar with `Microsoft.Extensions.DependencyInjection`.

Thank you for your advice!
