### ISSUE TITLE
Use `IAuthenticationHeaderExtractor` in `SignedRequestAuthenticationHandler`

### ISSUE THREAD

**Issue by anton-iades** [DavidLievrouw/HttpMessageSigning#37]
Currently, we can register a custom `IAuthenticationHeaderExtractor` for cases where the signature is not in the `Authorization` header.

Unfortunately, the [SignedRequestAuthenticationHandler](https://github.com/DavidLievrouw/HttpMessageSigning/blob/master/src/HttpMessageSigning.Verification.AspNetCore/SignedRequestAuthenticationHandler.cs) is currently hard-coded to expect an `Authorization` header explicitly - even though the actual verification uses the custom extractor.

Can these pre-conditions (lines [23](https://github.com/DavidLievrouw/HttpMessageSigning/blob/master/src/HttpMessageSigning.Verification.AspNetCore/SignedRequestAuthenticationHandler.cs#L23), [24](https://github.com/DavidLievrouw/HttpMessageSigning/blob/master/src/HttpMessageSigning.Verification.AspNetCore/SignedRequestAuthenticationHandler.cs#L24)) be replaced with a call to the `IAuthenticationHeaderExtractor` instead?

**Comment by DavidLievrouw** [comment]
Yes, I can't see why not.

Can you review commit https://github.com/DavidLievrouw/HttpMessageSigning/commit/cd8c8b7aa20a9930e9534aeb3562922448b94443, and see if it meets your needs? 

If so, I can release a patch version.

**Comment by anton-iades** [comment]
Thanks @DavidLievrouw - this perfectly meets my needs

**Comment by DavidLievrouw** [comment]
Released in [v6.3.1](https://github.com/DavidLievrouw/HttpMessageSigning/releases/tag/6.3.1).
