### ISSUE TITLE
hs2019 is not supported

### ISSUE THREAD

**Issue by blacktemplar** [DavidLievrouw/HttpMessageSigning#4]
The current version of the draft specification (https://tools.ietf.org/html/draft-cavage-http-signatures-12) enforces setting the algorithm parameter to "hs2019" effectively hiding the real used algorithm. All other options for the algorithm parameter are deprecated in [Appendix E.2](https://tools.ietf.org/html/draft-cavage-http-signatures-12#appendix-E.2).

This library should support setting the "hs2019". Note that this also changes the semantics of the draft at all positions where they explicitly state rules based on the algorithm parameter.

Furthermore for verification the library should support to provide the verifier with the real used algorithm based on the `keyId` value (i.e. some sort of callback) so that it can use this algorithm for verification if `algorithm=hs2019`.

**Comment by DavidLievrouw** [comment]
The signature will now specify value `hs2019` for `algorithm`, by default.

Added the `SigningSettings`.`UseDeprecatedAlgorithmParameter` property, to allow backwards compatibility.

Verifiers already use the `keyId` to get the algorithm to verify with. No changes needed there.

**Comment by dieterde** [comment]
Hi @DavidLievrouw ,

How does the #5 issue get fixed by this? And what timeframe do you see for or releasing this bugfix?
Thank you in advance for the information!

Best regards,
Dieter

**Comment by DavidLievrouw** [comment]
Hi @dieterde,

It was fixed in the branch created for issue #4. I noticed this issue too, before issue #5 was created.
So it was fixed when branch #4 was merged to master.
v4.0.0 was released a few minutes ago. Waiting for nuget.org indexing...

David

**Comment by dieterde** [comment]
Yes, it works. Big thank you!
